# Generated by Django 4.2.20 on 2025-04-06 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkingslot')),
            ],
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='category',
            field=models.CharField(blank=True, choices=[('2-wheeler', '2-Wheeler'), ('4-wheeler', '4-Wheeler'), ('heavy-load', 'Heavy Load')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.AddField(
            model_name='parkingrecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehicle'),
        ),
    ]
