# Generated by Django 4.2.20 on 2025-04-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingrecord_vehicletype_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingrecord',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
    ]
