# Generated by Django 4.2.20 on 2025-04-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_parkingrecord_amount_parkingrecord_payment_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='is_prebooked',
            field=models.BooleanField(default=False),
        ),
    ]
